Commit progress so far on pcretest (runs test 1 on interpreter).

diff --git a/RunTest b/RunTest
--- a/RunTest
+++ b/RunTest
@@ -100,8 +100,29 @@ case `$sim ./pcretest -C | $sim ./pcregrep 'Internal link size'` in
    *) echo "Failed to find internal link size"; exit 1;;
 esac
 
-$sim ./pcretest -C | $sim ./pcregrep 'No UTF-8 support' >/dev/null
-utf8=$?
+# Both 8-bit and 16-bit character strings may be supported, but only one
+# need be.
+
+$sim ./pcretest -C | $sim ./pcregrep '8-bit and 16-bit support' >/dev/null
+if [ $? -eq 0 ] ; then
+  test8=
+  test16=-16
+else
+  $sim ./pcretest -C | $sim ./pcregrep '8-bit support' >/dev/null
+  if [ $? -eq 0 ] ; then
+    test8=
+    test16=skip
+  else
+    test8=skip
+    test16=-16
+  fi
+fi
+           
+# UTF support always applies to both bit sizes if both are supported; we can't
+# have UTF-8 support without UTF-16 support (for example).
+
+$sim ./pcretest -C | $sim ./pcregrep 'No UTF-(.+?) support' >/dev/null
+utf=$?
 
 $sim ./pcretest -C | $sim ./pcregrep 'No Unicode properties support' >/dev/null
 ucp=$?
@@ -114,21 +135,21 @@ if [ $jit -ne 0 ] ; then
   jitopt=-s+
 fi
 
-if [ $utf8 -eq 0 ] ; then
+if [ $utf -eq 0 ] ; then
   if [ $do4 = yes ] ; then
-    echo "Can't run test 4 because UTF-8 support is not configured"
+    echo "Can't run test 4 because UTF support is not configured"
     exit 1
   fi
   if [ $do5 = yes ] ; then
-    echo "Can't run test 5 because UTF-8 support is not configured"
+    echo "Can't run test 5 because UTF support is not configured"
     exit 1
   fi
   if [ $do8 = yes ] ; then
-    echo "Can't run test 8 because UTF-8 support is not configured"
+    echo "Can't run test 8 because UTF support is not configured"
     exit 1
   fi
   if [ $do12 = yes ] ; then
-    echo "Can't run test 12 because UTF-8 support is not configured"
+    echo "Can't run test 12 because UTF support is not configured"
     exit 1
   fi
 fi
@@ -201,12 +222,20 @@ echo ""
 echo PCRE C library tests using test data from $testdata
 $sim ./pcretest /dev/null
 
+for bmode in "$test8" "$test16"; do
+  case "$bmode" in
+    skip) continue;;
+    -16)  if [ "$test8" != "skip" ] ; then echo ""; fi
+          echo "---- Testing 16-bit library ----"; echo "";;
+    *)    echo "---- Testing 8-bit library ----"; echo "";;
+  esac      
+   
 # Primary test, compatible with JIT and all versions of Perl >= 5.8
 
 if [ $do1 = yes ] ; then
   echo "Test 1: main functionality (Compatible with Perl >= 5.8)"
   for opt in "" "-s" $jitopt; do
-    $sim $valgrind ./pcretest -q $opt $testdata/testinput1 testtry
+    $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput1 testtry
     if [ $? = 0 ] ; then
       $cf $testdata/testoutput1 testtry
       if [ $? != 0 ] ; then exit 1; fi
@@ -222,9 +251,9 @@ fi
 # PCRE tests that are not JIT or Perl-compatible: API, errors, internals
 
 if [ $do2 = yes ] ; then
-  echo "Test 2: API, errors, internals, and non-Perl stuff (not UTF-8)"
+  echo "Test 2: API, errors, internals, and non-Perl stuff (not UTF-8/16)"
   for opt in "" "-s" $jitopt; do
-    $sim $valgrind ./pcretest -q $opt $testdata/testinput2 testtry
+    $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput2 testtry
     if [ $? = 0 ] ; then
       $cf $testdata/testoutput2 testtry
       if [ $? != 0 ] ; then exit 1; fi
@@ -278,7 +307,7 @@ if [ $do3 = yes ] ; then
   if [ "$locale" != "" ] ; then
     echo "Test 3: locale-specific features (using '$locale' locale)"
     for opt in "" "-s" $jitopt; do
-      $sim $valgrind ./pcretest -q $opt $infile testtry
+      $sim $valgrind ./pcretest -q $bmode $opt $infile testtry
       if [ $? = 0 ] ; then
         $cf $outfile testtry
         if [ $? != 0 ] ; then
@@ -304,15 +333,15 @@ if [ $do3 = yes ] ; then
   fi
 fi
 
-# Additional tests for UTF8 support
+# Additional tests for UTF support
 
 if [ $do4 = yes ] ; then
-  echo "Test 4: UTF-8 support (Compatible with Perl >= 5.8)"
-  if [ $utf8 -eq 0 ] ; then
-    echo "  Skipped because UTF-8 support is not available"
+  echo "Test 4: UTF-8/16 support (Compatible with Perl >= 5.8)"
+  if [ $utf -eq 0 ] ; then
+    echo "  Skipped because UTF support is not available"
   else
     for opt in "" "-s" $jitopt; do
-      $sim $valgrind ./pcretest -q $opt $testdata/testinput4 testtry
+      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput4 testtry
       if [ $? = 0 ] ; then
         $cf $testdata/testoutput4 testtry
         if [ $? != 0 ] ; then exit 1; fi
@@ -327,12 +356,12 @@ if [ $do4 = yes ] ; then
 fi
 
 if [ $do5 = yes ] ; then
-  echo "Test 5: API, internals, and non-Perl stuff for UTF-8 support"
-  if [ $utf8 -eq 0 ] ; then
-    echo "  Skipped because UTF-8 support is not available"
+  echo "Test 5: API, internals, and non-Perl stuff for UTF-8/16 support"
+  if [ $utf -eq 0 ] ; then
+    echo "  Skipped because UTF support is not available"
   else
     for opt in "" "-s" $jitopt; do
-      $sim $valgrind ./pcretest -q $opt $testdata/testinput5 testtry
+      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput5 testtry
       if [ $? = 0 ] ; then
         $cf $testdata/testoutput5 testtry
         if [ $? != 0 ] ; then exit 1; fi
@@ -348,11 +377,11 @@ fi
 
 if [ $do6 = yes ] ; then
   echo "Test 6: Unicode property support (Compatible with Perl >= 5.10)"
-  if [ $utf8 -eq 0 -o $ucp -eq 0 ] ; then
+  if [ $utf -eq 0 -o $ucp -eq 0 ] ; then
     echo "  Skipped because Unicode property support is not available"
   else
     for opt in "" "-s" $jitopt; do
-      $sim $valgrind ./pcretest -q $opt $testdata/testinput6 testtry
+      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput6 testtry
       if [ $? = 0 ] ; then
         $cf $testdata/testoutput6 testtry
         if [ $? != 0 ] ; then exit 1; fi
@@ -371,7 +400,7 @@ fi
 if [ $do7 = yes ] ; then
   echo "Test 7: DFA matching"
   for opt in "" "-s"; do
-    $sim $valgrind ./pcretest -q $opt -dfa $testdata/testinput7 testtry
+    $sim $valgrind ./pcretest -q $bmode $opt -dfa $testdata/testinput7 testtry
     if [ $? = 0 ] ; then
       $cf $testdata/testoutput7 testtry
       if [ $? != 0 ] ; then exit 1; fi
@@ -382,12 +411,12 @@ if [ $do7 = yes ] ; then
 fi
 
 if [ $do8 = yes ] ; then
-  echo "Test 8: DFA matching with UTF-8"
-  if [ $utf8 -eq 0 ] ; then
-    echo "  Skipped because UTF-8 support is not available"
+  echo "Test 8: DFA matching with UTF-8 or UTF-16"
+  if [ $utf -eq 0 ] ; then
+    echo "  Skipped because UTF support is not available"
   else
     for opt in "" "-s"; do
-      $sim $valgrind ./pcretest -q $opt -dfa $testdata/testinput8 testtry
+      $sim $valgrind ./pcretest -q $bmode $opt -dfa $testdata/testinput8 testtry
       if [ $? = 0 ] ; then
         $cf $testdata/testoutput8 testtry
         if [ $? != 0 ] ; then exit 1; fi
@@ -400,11 +429,11 @@ fi
 
 if [ $do9 = yes ] ; then
   echo "Test 9: DFA matching with Unicode properties"
-  if [ $utf8 -eq 0 -o $ucp -eq 0 ] ; then
+  if [ $utf -eq 0 -o $ucp -eq 0 ] ; then
     echo "  Skipped because Unicode property support is not available"
   else
     for opt in "" "-s"; do
-      $sim $valgrind ./pcretest -q $opt -dfa $testdata/testinput9 testtry
+      $sim $valgrind ./pcretest -q $bmode $opt -dfa $testdata/testinput9 testtry
       if [ $? = 0 ] ; then
         $cf $testdata/testoutput9 testtry
         if [ $? != 0 ] ; then exit 1; fi
@@ -429,7 +458,7 @@ if [ $do10 = yes ] ; then
     echo "  Skipped because Unicode property support is not available"
   else
     for opt in "" "-s"; do
-      $sim $valgrind ./pcretest -q $opt $testdata/testinput10 testtry
+      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput10 testtry
       if [ $? = 0 ] ; then
         $cf $testdata/testoutput10 testtry
         if [ $? != 0 ] ; then exit 1; fi
@@ -445,7 +474,7 @@ fi
 if [ $do11 = yes ] ; then
   echo "Test 11: Features from Perl >= 5.10 without UTF8 support"
   for opt in "" "-s" $jitopt; do
-    $sim $valgrind ./pcretest -q $opt $testdata/testinput11 testtry
+    $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput11 testtry
     if [ $? = 0 ] ; then
       $cf $testdata/testoutput11 testtry
       if [ $? != 0 ] ; then exit 1; fi
@@ -461,12 +490,12 @@ fi
 # Test of Perl >= 5.10 features with UTF8 support
 
 if [ $do12 = yes ] ; then
-  echo "Test 12: Features from Perl >= 5.10 with UTF8 support"
-  if [ $utf8 -eq 0 ] ; then
-    echo "  Skipped because UTF-8 support is not available"
+  echo "Test 12: Features from Perl >= 5.10 with UTF-8 or UTF-16 support"
+  if [ $utf -eq 0 ] ; then
+    echo "  Skipped because UTF support is not available"
   else
     for opt in "" "-s" $jitopt; do
-      $sim $valgrind ./pcretest -q $opt $testdata/testinput12 testtry
+      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput12 testtry
       if [ $? = 0 ] ; then
         $cf $testdata/testoutput12 testtry
         if [ $? != 0 ] ; then exit 1; fi
@@ -484,11 +513,11 @@ fi
 
 if [ $do13 = yes ] ; then
   echo "Test 13: API, internals, and non-Perl stuff for Unicode property support"
-  if [ $utf8 -eq 0 -o $ucp -eq 0 ] ; then
+  if [ $utf -eq 0 -o $ucp -eq 0 ] ; then
     echo "  Skipped because Unicode property support is not available"
   else
     for opt in "" "-s" $jitopt; do
-      $sim $valgrind ./pcretest -q $opt $testdata/testinput13 testtry
+      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput13 testtry
       if [ $? = 0 ] ; then
         $cf $testdata/testoutput13 testtry
         if [ $? != 0 ] ; then exit 1; fi
@@ -509,7 +538,7 @@ if [ $do14 = yes ] ; then
   if [ $jit -eq 0 ] ; then
     echo "  Skipped because JIT is not available or not usable"
   else
-    $sim $valgrind ./pcretest -q $testdata/testinput14 testtry
+    $sim $valgrind ./pcretest -q $bmode $testdata/testinput14 testtry
     if [ $? = 0 ] ; then
       $cf $testdata/testoutput14 testtry
       if [ $? != 0 ] ; then exit 1; fi
@@ -526,7 +555,7 @@ if [ $do15 = yes ] ; then
   if [ $jit -ne 0 ] ; then
     echo "  Skipped because JIT is available"
   else
-    $sim $valgrind ./pcretest -q $testdata/testinput15 testtry
+    $sim $valgrind ./pcretest -q $bmode $testdata/testinput15 testtry
     if [ $? = 0 ] ; then
       $cf $testdata/testoutput15 testtry
       if [ $? != 0 ] ; then exit 1; fi
@@ -535,5 +564,9 @@ if [ $do15 = yes ] ; then
     echo "  OK"
   fi
 fi
+
+# End of loop for 8-bit/16-bit tests
+
+done
 
 # End
