Reorganized the tests and made many more work in 16-bit mode.

diff --git a/RunTest b/RunTest
--- a/RunTest
+++ b/RunTest
@@ -52,6 +52,8 @@ do14=no
 do15=no
 do16=no
 do17=no
+do18=no
+do19=no
 
 while [ $# -gt 0 ] ; do
   case $1 in
@@ -71,7 +73,9 @@ while [ $# -gt 0 ] ; do
    14) do14=yes;;
    15) do15=yes;;
    16) do16=yes;;
-   17) do17=yes;;  
+   17) do17=yes;;
+   18) do18=yes;;
+   19) do19=yes;;
    -8) arg8=yes;;
   -16) arg16=yes;;   
    valgrind) valgrind="valgrind -q --smc-check=all";;
@@ -161,15 +165,31 @@ if [ $jit -ne 0 ] ; then
 fi
 
 if [ "$test8" = skip ] ; then
-  if [ $do17 = yes ] ; then
-    echo "Can't run test 17 because the 8-bit library is not built"
+  if [ $do14 = yes ] ; then
+    echo "Can't run test 14 because the 8-bit library is not built"
+    exit 1
+  fi     
+  if [ $do15 = yes ] ; then
+    echo "Can't run test 15 because the 8-bit library is not built"
+    exit 1
+  fi     
+  if [ $do16 = yes ] ; then
+    echo "Can't run test 16 because the 8-bit library is not built"
     exit 1
   fi     
 fi
 
-if [ "$test16" = skip ] ; then
-  if [ $do16 = yes ] ; then
-    echo "Can't run test 16 because the 16-bit library is not built"
+if [ "$test17" = skip ] ; then
+  if [ $do17 = yes ] ; then
+    echo "Can't run test 17 because the 16-bit library is not built"
+    exit 1
+  fi     
+  if [ $do18 = yes ] ; then
+    echo "Can't run test 18 because the 16-bit library is not built"
+    exit 1
+  fi     
+  if [ $do19 = yes ] ; then
+    echo "Can't run test 19 because the 16-bit library is not built"
     exit 1
   fi     
 fi
@@ -183,19 +203,16 @@ if [ $utf -eq 0 ] ; then
     echo "Can't run test 5 because UTF support is not configured"
     exit 1
   fi
-  if [ $do8 = yes ] ; then
+  if [ $do9 = yes ] ; then
     echo "Can't run test 8 because UTF support is not configured"
     exit 1
   fi
-  if [ $do12 = yes ] ; then
-    echo "Can't run test 12 because UTF support is not configured"
+  if [ $do15 = yes ] ; then
+    echo "Can't run test 15 because UTF support is not configured"
     exit 1
   fi
-  if [ $do16 = yes ] ; then
-    echo "Can't run test 16 because UTF support is not configured"
-  fi     
-  if [ $do17 = yes ] ; then
-    echo "Can't run test 17 because UTF support is not configured"
+  if [ $do18 = yes ] ; then
+    echo "Can't run test 18 because UTF support is not configured"
   fi     
 fi
 
@@ -204,35 +221,39 @@ if [ $ucp -eq 0 ] ; then
     echo "Can't run test 6 because Unicode property support is not configured"
     exit 1
   fi
-  if [ $do9 = yes ] ; then
-    echo "Can't run test 9 because Unicode property support is not configured"
+  if [ $do7 = yes ] ; then
+    echo "Can't run test 7 because Unicode property support is not configured"
     exit 1
   fi
   if [ $do10 = yes ] ; then
     echo "Can't run test 10 because Unicode property support is not configured"
     exit 1
   fi
-  if [ $do13 = yes ] ; then
-    echo "Can't run test 12 because Unicode property support is not configured"
+  if [ $do16 = yes ] ; then
+    echo "Can't run test 16 because Unicode property support is not configured"
+    exit 1
+  fi
+  if [ $do19 = yes ] ; then
+    echo "Can't run test 19 because Unicode property support is not configured"
     exit 1
   fi
 fi
 
 if [ $link_size -ne 2 ] ; then
-  if [ $do10 = yes ] ; then
-    echo "Can't run test 10 because the link size ($link_size) is not 2"
+  if [ $do11 = yes ] ; then
+    echo "Can't run test 11 because the link size ($link_size) is not 2"
     exit 1
   fi
 fi
 
 if [ $jit -eq 0 ] ; then
-  if [ $do14 = "yes" ] ; then
-    echo "Can't run test 14 because JIT support is not configured"
+  if [ $do12 = "yes" ] ; then
+    echo "Can't run test 12 because JIT support is not configured"
     exit 1
   fi
 else
-  if [ $do15 = "yes" ] ; then
-    echo "Can't run test 15 because JIT support is configured"
+  if [ $do13 = "yes" ] ; then
+    echo "Can't run test 13 because JIT support is configured"
     exit 1
   fi
 fi
@@ -244,7 +265,7 @@ if [ $do1  = no -a $do2  = no -a $do3  = no -a $do4  = no -a \
      $do5  = no -a $do6  = no -a $do7  = no -a $do8  = no -a \
      $do9  = no -a $do10 = no -a $do11 = no -a $do12 = no -a \
      $do13 = no -a $do14 = no -a $do15 = no -a $do16 = no -a \
-     $do17 = no ] ; then
+     $do17 = no -a $do18 = no -a $do19 = no ] ; then
   do1=yes
   do2=yes
   do3=yes
@@ -261,7 +282,9 @@ if [ $do1  = no -a $do2  = no -a $do3  = no -a $do4  = no -a \
   do14=yes
   do15=yes
   do16=yes
-  do17=yes  
+  do17=yes
+  do18=yes
+  do19=yes
 fi
 
 # Show which release and which test data
@@ -281,7 +304,7 @@ for bmode in "$test8" "$test16"; do
 # Primary test, compatible with JIT and all versions of Perl >= 5.8
 
 if [ $do1 = yes ] ; then
-  echo "Test 1: main functionality (Compatible with Perl >= 5.8)"
+  echo "Test 1: main functionality (Compatible with Perl >= 5.10)"
   for opt in "" "-s" $jitopt; do
     $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput1 testtry
     if [ $? = 0 ] ; then
@@ -384,7 +407,7 @@ fi
 # Additional tests for UTF support
 
 if [ $do4 = yes ] ; then
-  echo "Test 4: UTF-$bits support (Compatible with Perl >= 5.8)"
+  echo "Test 4: UTF-$bits support (Compatible with Perl >= 5.10)"
   if [ $utf -eq 0 ] ; then
     echo "  Skipped because UTF-$bits support is not available"
   else
@@ -443,14 +466,36 @@ if [ $do6 = yes ] ; then
   fi
 fi
 
-# Tests for DFA matching support
+# Test non-Perl-compatible Unicode property support
 
 if [ $do7 = yes ] ; then
-  echo "Test 7: DFA matching"
+  echo "Test 7: API, internals, and non-Perl stuff for Unicode property support"
+  if [ $utf -eq 0 -o $ucp -eq 0 ] ; then
+    echo "  Skipped because Unicode property support is not available"
+  else
+    for opt in "" "-s" $jitopt; do
+      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput7 testtry
+      if [ $? = 0 ] ; then
+        $cf $testdata/testoutput7 testtry
+        if [ $? != 0 ] ; then exit 1; fi
+      else exit 1
+      fi
+      if [ "$opt" = "-s" ] ; then echo "  OK with study"
+      elif [ "$opt" = "-s+" ] ; then echo "  OK with JIT study"
+      else echo "  OK"
+      fi
+    done
+  fi
+fi
+
+# Tests for DFA matching support
+
+if [ $do8 = yes ] ; then
+  echo "Test 8: DFA matching main functionality"
   for opt in "" "-s"; do
-    $sim $valgrind ./pcretest -q $bmode $opt -dfa $testdata/testinput7 testtry
+    $sim $valgrind ./pcretest -q $bmode $opt -dfa $testdata/testinput8 testtry
     if [ $? = 0 ] ; then
-      $cf $testdata/testoutput7 testtry
+      $cf $testdata/testoutput8 testtry
       if [ $? != 0 ] ; then exit 1; fi
     else exit 1
     fi
@@ -458,27 +503,10 @@ if [ $do7 = yes ] ; then
   done
 fi
 
-if [ $do8 = yes ] ; then
-  echo "Test 8: DFA matching with UTF-$bits"
+if [ $do9 = yes ] ; then
+  echo "Test 9: DFA matching with UTF-$bits"
   if [ $utf -eq 0 ] ; then
     echo "  Skipped because UTF-$bits support is not available"
-  else
-    for opt in "" "-s"; do
-      $sim $valgrind ./pcretest -q $bmode $opt -dfa $testdata/testinput8 testtry
-      if [ $? = 0 ] ; then
-        $cf $testdata/testoutput8 testtry
-        if [ $? != 0 ] ; then exit 1; fi
-      else exit 1
-      fi
-      if [ "$opt" = "-s" ] ; then echo "  OK with study" ; else echo "  OK"; fi
-    done
-  fi
-fi
-
-if [ $do9 = yes ] ; then
-  echo "Test 9: DFA matching with Unicode properties"
-  if [ $utf -eq 0 -o $ucp -eq 0 ] ; then
-    echo "  Skipped because Unicode property support is not available"
   else
     for opt in "" "-s"; do
       $sim $valgrind ./pcretest -q $bmode $opt -dfa $testdata/testinput9 testtry
@@ -492,21 +520,13 @@ if [ $do9 = yes ] ; then
   fi
 fi
 
-# Test of internal offsets and code sizes. This test is run only when there
-# is Unicode property support and the link size is 2. The actual tests are
-# mostly the same as in some of the above, but in this test we inspect some
-# offsets and sizes that require a known link size. This is a doublecheck for
-# the maintainer, just in case something changes unexpectely.
-
 if [ $do10 = yes ] ; then
-  echo "Test 10: Internal offsets and code size tests"
-  if [ $link_size -ne 2 ] ; then
-    echo "  Skipped because link size is not 2"
-  elif [ $ucp -eq 0 ] ; then
+  echo "Test 10: DFA matching with Unicode properties"
+  if [ $utf -eq 0 -o $ucp -eq 0 ] ; then
     echo "  Skipped because Unicode property support is not available"
   else
     for opt in "" "-s"; do
-      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput10 testtry
+      $sim $valgrind ./pcretest -q $bmode $opt -dfa $testdata/testinput10 testtry
       if [ $? = 0 ] ; then
         $cf $testdata/testoutput10 testtry
         if [ $? != 0 ] ; then exit 1; fi
@@ -517,78 +537,42 @@ if [ $do10 = yes ] ; then
   fi
 fi
 
-# Test of Perl >= 5.10 features without UTF support
+# Test of internal offsets and code sizes. This test is run only when there
+# is Unicode property support and the link size is 2. The actual tests are
+# mostly the same as in some of the above, but in this test we inspect some
+# offsets and sizes that require a known link size. This is a doublecheck for
+# the maintainer, just in case something changes unexpectely. The output from
+# this test is not the same in 8-bit and 16-bit modes.
 
 if [ $do11 = yes ] ; then
-  echo "Test 11: Features from Perl >= 5.10 without UTF-$bits support"
-  for opt in "" "-s" $jitopt; do
-    $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput11 testtry
-    if [ $? = 0 ] ; then
-      $cf $testdata/testoutput11 testtry
-      if [ $? != 0 ] ; then exit 1; fi
-    else exit 1
-    fi
-    if [ "$opt" = "-s" ] ; then echo "  OK with study"
-    elif [ "$opt" = "-s+" ] ; then echo "  OK with JIT study"
-    else echo "  OK"
-    fi
-  done
-fi
-
-# Test of Perl >= 5.10 features with UTF support
-
-if [ $do12 = yes ] ; then
-  echo "Test 12: Features from Perl >= 5.10 with UTF-$bits support"
-  if [ $utf -eq 0 ] ; then
-    echo "  Skipped because UTF-$bits support is not available"
-  else
-    for opt in "" "-s" $jitopt; do
-      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput12 testtry
-      if [ $? = 0 ] ; then
-        $cf $testdata/testoutput12 testtry
-        if [ $? != 0 ] ; then exit 1; fi
-      else exit 1
-      fi
-      if [ "$opt" = "-s" ] ; then echo "  OK with study"
-      elif [ "$opt" = "-s+" ] ; then echo "  OK with JIT study"
-      else echo "  OK"
-      fi
-    done
-  fi
-fi
-
-# Test non-Perl-compatible Unicode property support
-
-if [ $do13 = yes ] ; then
-  echo "Test 13: API, internals, and non-Perl stuff for Unicode property support"
-  if [ $utf -eq 0 -o $ucp -eq 0 ] ; then
+  echo "Test 11: Internal offsets and code size tests"
+  if [ $link_size -ne 2 ] ; then
+    echo "  Skipped because link size is not 2"
+  elif [ $ucp -eq 0 ] ; then
     echo "  Skipped because Unicode property support is not available"
   else
-    for opt in "" "-s" $jitopt; do
-      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput13 testtry
+    for opt in "" "-s"; do
+      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput11 testtry
       if [ $? = 0 ] ; then
-        $cf $testdata/testoutput13 testtry
+        $cf $testdata/testoutput11-$bits testtry
         if [ $? != 0 ] ; then exit 1; fi
       else exit 1
       fi
-      if [ "$opt" = "-s" ] ; then echo "  OK with study"
-      elif [ "$opt" = "-s+" ] ; then echo "  OK with JIT study"
-      else echo "  OK"
-      fi
+      if [ "$opt" = "-s" ] ; then echo "  OK with study" ; else echo "  OK"; fi
     done
   fi
 fi
 
 # Test JIT-specific features when JIT is available
 
-if [ $do14 = yes ] ; then
-  echo "Test 14: JIT-specific features (JIT available)"
+if [ $do12 = yes ] ; then
+  echo "Test 12: JIT-specific features (JIT available)"
   if [ $jit -eq 0 ] ; then
     echo "  Skipped because JIT is not available or not usable"
   else
-    $sim $valgrind ./pcretest -q $bmode $testdata/testinput14 testtry
+    $sim $valgrind ./pcretest -q $bmode $testdata/testinput12 testtry
     if [ $? = 0 ] ; then
-      $cf $testdata/testoutput14 testtry
+      $cf $testdata/testoutput12 testtry
       if [ $? != 0 ] ; then exit 1; fi
     else exit 1
     fi
@@ -598,14 +582,14 @@ fi
 
 # Test JIT-specific features when JIT is not available
 
-if [ $do15 = yes ] ; then
-  echo "Test 15: JIT-specific features (JIT not available)"
+if [ $do13 = yes ] ; then
+  echo "Test 13: JIT-specific features (JIT not available)"
   if [ $jit -ne 0 ] ; then
     echo "  Skipped because JIT is available"
   else
-    $sim $valgrind ./pcretest -q $bmode $testdata/testinput15 testtry
+    $sim $valgrind ./pcretest -q $bmode $testdata/testinput13 testtry
     if [ $? = 0 ] ; then
-      $cf $testdata/testoutput15 testtry
+      $cf $testdata/testoutput13 testtry
       if [ $? != 0 ] ; then exit 1; fi
     else exit 1
     fi
@@ -613,14 +597,62 @@ if [ $do15 = yes ] ; then
   fi
 fi
 
-# Tests for 16-bit-specific features (needs UTF-8 support)
+# Tests for 8-bit-specific features
 
-if [ $do16 = yes ] ; then
-  echo "Test 16: specials for the 16-bit library"
-  if [ "$bits" = "8" ] ; then
-    echo "  Skipped when running 8-bit tests"
+if [ "$do14" = yes ] ; then
+  echo "Test 14: specials for the basic 8-bit library"
+  if [ "$bits" = "16" ] ; then
+    echo "  Skipped when running 16-bit tests"
   elif [ $utf -eq 0 ] ; then
     echo "  Skipped because UTF-$bits support is not available"
+  else   
+    for opt in "" "-s" $jitopt; do
+      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput14 testtry
+      if [ $? = 0 ] ; then
+        $cf $testdata/testoutput14 testtry
+        if [ $? != 0 ] ; then exit 1; fi
+      else exit 1
+      fi
+      if [ "$opt" = "-s" ] ; then echo "  OK with study"
+      elif [ "$opt" = "-s+" ] ; then echo "  OK with JIT study"
+      else echo "  OK"
+      fi
+    done
+  fi
+fi
+
+# Tests for 8-bit-specific features (needs UTF-8 support)
+
+if [ "$do15" = yes ] ; then
+  echo "Test 15: specials for the 8-bit library with UTF-8 support"
+  if [ "$bits" = "16" ] ; then
+    echo "  Skipped when running 16-bit tests"
+  elif [ $utf -eq 0 ] ; then
+    echo "  Skipped because UTF-$bits support is not available"
+  else   
+    for opt in "" "-s" $jitopt; do
+      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput15 testtry
+      if [ $? = 0 ] ; then
+        $cf $testdata/testoutput15 testtry
+        if [ $? != 0 ] ; then exit 1; fi
+      else exit 1
+      fi
+      if [ "$opt" = "-s" ] ; then echo "  OK with study"
+      elif [ "$opt" = "-s+" ] ; then echo "  OK with JIT study"
+      else echo "  OK"
+      fi
+    done
+  fi
+fi
+
+# Tests for 8-bit-specific features (Unicode property support)
+
+if [ $do16 = yes ] ; then
+  echo "Test 16: specials for the 8-bit library with Unicode propery support"
+  if [ "$bits" = "16" ] ; then
+    echo "  Skipped when running 16-bit tests"
+  elif [ $ucp -eq 0 ] ; then
+    echo "  Skipped because Unicode property support is not available"
   else   
     for opt in "" "-s" $jitopt; do
       $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput16 testtry
@@ -637,19 +669,65 @@ if [ $do16 = yes ] ; then
   fi
 fi
 
-# Tests for 8-bit-specific features (needs UTF-8 support)
+# Tests for 16-bit-specific features
 
 if [ $do17 = yes ] ; then
-  echo "Test 17: specials for the 8-bit library"
-  if [ "$bits" = "16" ] ; then
-    echo "  Skipped when running 16-bit tests"
-  elif [ $utf -eq 0 ] ; then
-    echo "  Skipped because UTF-$bits support is not available"
+  echo "Test 17: specials for the basic 16-bit library"
+  if [ "$bits" = "8" ] ; then
+    echo "  Skipped when running 8-bit tests"
   else   
     for opt in "" "-s" $jitopt; do
       $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput17 testtry
       if [ $? = 0 ] ; then
         $cf $testdata/testoutput17 testtry
+        if [ $? != 0 ] ; then exit 1; fi
+      else exit 1
+      fi
+      if [ "$opt" = "-s" ] ; then echo "  OK with study"
+      elif [ "$opt" = "-s+" ] ; then echo "  OK with JIT study"
+      else echo "  OK"
+      fi
+    done
+  fi
+fi
+
+# Tests for 16-bit-specific features (UTF-16 support)
+
+if [ $do18 = yes ] ; then
+  echo "Test 18: specials for the 16-bit library with UTF-16 support"
+  if [ "$bits" = "8" ] ; then
+    echo "  Skipped when running 8-bit tests"
+  elif [ $utf -eq 0 ] ; then
+    echo "  Skipped because UTF-$bits support is not available"
+  else   
+    for opt in "" "-s" $jitopt; do
+      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput18 testtry
+      if [ $? = 0 ] ; then
+        $cf $testdata/testoutput18 testtry
+        if [ $? != 0 ] ; then exit 1; fi
+      else exit 1
+      fi
+      if [ "$opt" = "-s" ] ; then echo "  OK with study"
+      elif [ "$opt" = "-s+" ] ; then echo "  OK with JIT study"
+      else echo "  OK"
+      fi
+    done
+  fi
+fi
+
+# Tests for 16-bit-specific features (Unicode property support)
+
+if [ $do19 = yes ] ; then
+  echo "Test 19: specials for the 16-bit library with Unicode propery support"
+  if [ "$bits" = "8" ] ; then
+    echo "  Skipped when running 8-bit tests"
+  elif [ $ucp -eq 0 ] ; then
+    echo "  Skipped because Unicode property support is not available"
+  else   
+    for opt in "" "-s" $jitopt; do
+      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput19 testtry
+      if [ $? = 0 ] ; then
+        $cf $testdata/testoutput19 testtry
         if [ $? != 0 ] ; then exit 1; fi
       else exit 1
       fi
